const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CLUSTER_ADMIN: 'CLUSTER_ADMIN',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  ACADEMIC_AFFAIRS: 'ACADEMIC_AFFAIRS',
  SUBJECT_TEACHER: 'SUBJECT_TEACHER',
  HOMEROOM_TEACHER: 'HOMEROOM_TEACHER',
  ACCOUNTANT: 'ACCOUNTANT',
  LIBRARIAN: 'LIBRARIAN',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
};

const ROLE_LABELS = {
  SUPER_ADMIN: 'Super Admin',
  CLUSTER_ADMIN: 'Quản lý cụm trường',
  SCHOOL_ADMIN: 'Hiệu trưởng / Ban giám hiệu',
  ACADEMIC_AFFAIRS: 'Giáo vụ / Văn thư',
  SUBJECT_TEACHER: 'Giáo viên bộ môn',
  HOMEROOM_TEACHER: 'Giáo viên chủ nhiệm',
  ACCOUNTANT: 'Kế toán / Thủ quỹ',
  LIBRARIAN: 'Thủ thư / Quản lý CSVC',
  STUDENT: 'Học sinh',
  PARENT: 'Phụ huynh',
};

const ALL_ROLES = Object.values(ROLES);

const SCHOOL_SCOPED_ROLES = [
  ROLES.SCHOOL_ADMIN,
  ROLES.ACADEMIC_AFFAIRS,
  ROLES.SUBJECT_TEACHER,
  ROLES.HOMEROOM_TEACHER,
  ROLES.ACCOUNTANT,
  ROLES.LIBRARIAN,
  ROLES.STUDENT,
  ROLES.PARENT,
];

module.exports = {
  ROLES,
  ROLE_LABELS,
  ALL_ROLES,
  SCHOOL_SCOPED_ROLES,
};
