const { ROLES } = require('./roles');
const { entriesSatisfyLegacy } = require('./permissionCatalog');

const PERMISSIONS = {
  MANAGE_TENANTS: 'MANAGE_TENANTS',
  MANAGE_CLUSTERS: 'MANAGE_CLUSTERS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_STRUCTURE: 'MANAGE_STRUCTURE',
  MANAGE_TIMETABLE: 'MANAGE_TIMETABLE',
  TAKE_ATTENDANCE: 'TAKE_ATTENDANCE',
  ENTER_GRADES: 'ENTER_GRADES',
  MANAGE_FEES: 'MANAGE_FEES',
  MANAGE_ANNOUNCEMENTS: 'MANAGE_ANNOUNCEMENTS',
  MANAGE_LEAVE: 'MANAGE_LEAVE',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_OWN_DATA: 'VIEW_OWN_DATA',
  MANAGE_SUBSCRIPTIONS: 'MANAGE_SUBSCRIPTIONS',
  MANAGE_EXAMS: 'MANAGE_EXAMS',
  TAKE_EXAMS: 'TAKE_EXAMS',
  MANAGE_MATERIALS: 'MANAGE_MATERIALS',
  MANAGE_LIBRARY: 'MANAGE_LIBRARY',
  MANAGE_FACILITIES: 'MANAGE_FACILITIES',
  VIEW_AUDIT: 'VIEW_AUDIT',
  MANAGE_SUPPORT: 'MANAGE_SUPPORT',
  MANAGE_CONDUCT: 'MANAGE_CONDUCT',
  MANAGE_TEMPLATES: 'MANAGE_TEMPLATES',
  MANAGE_ROLES: 'MANAGE_ROLES',
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.CLUSTER_ADMIN]: [
    PERMISSIONS.MANAGE_CLUSTERS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_LEAVE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_TEMPLATES,
    PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.MANAGE_ROLES,
  ],
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_STRUCTURE,
    PERMISSIONS.MANAGE_TIMETABLE,
    PERMISSIONS.TAKE_ATTENDANCE,
    PERMISSIONS.ENTER_GRADES,
    PERMISSIONS.MANAGE_FEES,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_LEAVE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_EXAMS,
    PERMISSIONS.MANAGE_MATERIALS,
    PERMISSIONS.VIEW_AUDIT,
    PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.MANAGE_CONDUCT,
    PERMISSIONS.MANAGE_TEMPLATES,
    PERMISSIONS.MANAGE_ROLES,
  ],
  [ROLES.ACADEMIC_AFFAIRS]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_STRUCTURE,
    PERMISSIONS.MANAGE_TIMETABLE,
    PERMISSIONS.TAKE_ATTENDANCE,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_LEAVE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_EXAMS,
    PERMISSIONS.MANAGE_MATERIALS,
    PERMISSIONS.MANAGE_FACILITIES,
  ],
  [ROLES.SUBJECT_TEACHER]: [
    PERMISSIONS.TAKE_ATTENDANCE,
    PERMISSIONS.ENTER_GRADES,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_LEAVE,
    PERMISSIONS.VIEW_OWN_DATA,
    PERMISSIONS.MANAGE_EXAMS,
    PERMISSIONS.MANAGE_MATERIALS,
    PERMISSIONS.MANAGE_FACILITIES,
  ],
  [ROLES.HOMEROOM_TEACHER]: [
    PERMISSIONS.TAKE_ATTENDANCE,
    PERMISSIONS.ENTER_GRADES,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_LEAVE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_OWN_DATA,
    PERMISSIONS.MANAGE_EXAMS,
    PERMISSIONS.MANAGE_MATERIALS,
    PERMISSIONS.MANAGE_CONDUCT,
    PERMISSIONS.MANAGE_FACILITIES,
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.MANAGE_FEES,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.LIBRARIAN]: [
    PERMISSIONS.MANAGE_LIBRARY,
    PERMISSIONS.MANAGE_FACILITIES,
    PERMISSIONS.VIEW_OWN_DATA,
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_OWN_DATA,
    PERMISSIONS.MANAGE_LEAVE,
    PERMISSIONS.TAKE_EXAMS,
  ],
  [ROLES.PARENT]: [PERMISSIONS.VIEW_OWN_DATA, PERMISSIONS.MANAGE_LEAVE],
};

const hasPermission = (role, permission) => {
  if (role === ROLES.SUPER_ADMIN) return true;
  try {
    const roleCache = require('../services/rolePermissionCache');
    return roleCache.hasPermissionLegacySync(role, permission);
  } catch {
    return (ROLE_PERMISSIONS[role] || []).includes(permission);
  }
};

const hasPermissionAsync = async (role, permission) => {
  if (role === ROLES.SUPER_ADMIN) return true;
  const roleCache = require('../services/rolePermissionCache');
  return roleCache.hasPermissionLegacy(role, permission);
};

const listLegacyPermissionsForRole = async (roleCode) => {
  if (roleCode === ROLES.SUPER_ADMIN) return Object.values(PERMISSIONS);
  const roleCache = require('../services/rolePermissionCache');
  await roleCache.ensureLoaded();
  const role = await roleCache.getRole(roleCode);
  if (!role) return ROLE_PERMISSIONS[roleCode] || [];
  return Object.values(PERMISSIONS).filter((p) => entriesSatisfyLegacy(role.permissions, p));
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  hasPermissionAsync,
  listLegacyPermissionsForRole,
};
