const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING: 'PENDING',
};

const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const LEAVE_TYPES = {
  STUDENT_ABSENCE: 'STUDENT_ABSENCE',
  TEACHER_ABSENCE: 'TEACHER_ABSENCE',
  MAKEUP_CLASS: 'MAKEUP_CLASS',
};

const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT_EXCUSED: 'ABSENT_EXCUSED',
  ABSENT_UNEXCUSED: 'ABSENT_UNEXCUSED',
  LATE: 'LATE',
};

const GRADE_TYPES = {
  ORAL: 'ORAL',
  QUIZ_15: 'QUIZ_15',
  MIDTERM: 'MIDTERM',
  FINAL: 'FINAL',
};

const FEE_STATUS = {
  UNPAID: 'UNPAID',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
};

const ANNOUNCEMENT_SCOPE = {
  SYSTEM: 'SYSTEM',
  CLUSTER: 'CLUSTER',
  SCHOOL: 'SCHOOL',
  CLASS: 'CLASS',
};

module.exports = {
  STATUS,
  LEAVE_STATUS,
  LEAVE_TYPES,
  ATTENDANCE_STATUS,
  GRADE_TYPES,
  FEE_STATUS,
  ANNOUNCEMENT_SCOPE,
};
