const express = require('express');
const router = express.Router();

// Feature registrars share this Router to preserve the original middleware and route order.
require('../admin/job.routes').register1(router);
require('./file.routes').register1(router);
require('../admin/student-document.routes').register1(router);
require('./system.routes').register1(router);
require('../admin/monitoring.routes').register1(router);
require('./platform.routes').register1(router);
require('./auth.routes').register1(router);
require('./dashboard.routes').register1(router);
require('./notification.routes').register1(router);
require('./dashboard.routes').register2(router);
require('../admin/tenant.routes').register1(router);
require('../admin/user.routes').register1(router);
require('../admin/role.routes').register1(router);
require('../admin/academic.routes').register1(router);
require('../teacher/attendance.routes').register1(router);
require('../teacher/grade.routes').register1(router);
require('../finance/fee.routes').register1(router);
require('../finance/payroll.routes').register1(router);
require('./equipment.routes').register1(router);
require('./online-payment.routes').register1(router);
require('./appointment.routes').register1(router);
require('../teacher/reward.routes').register1(router);
require('../admin/admission.routes').register1(router);
require('./announcement.routes').register1(router);
require('./leave.routes').register1(router);
require('./teaching-schedule.routes').register1(router);
require('../admin/timetable.routes').register1(router);
require('../admin/subscription.routes').register1(router);
require('../admin/template.routes').register1(router);
require('./exam.routes').register1(router);
require('./homework.routes').register1(router);
require('./file.routes').register2(router);
require('./homework.routes').register2(router);
require('../teacher/lesson-plan.routes').register1(router);
require('../teacher/contact-book.routes').register1(router);
require('../teacher/class-life.routes').register1(router);
require('./club.routes').register1(router);
require('../teacher/material.routes').register1(router);
require('../operations/library.routes').register1(router);
require('./facility.routes').register1(router);
require('../admin/audit.routes').register1(router);
require('../admin/support.routes').register1(router);
require('../teacher/conduct.routes').register1(router);
require('../admin/template.routes').register2(router);
require('./message.routes').register1(router);
require('./calendar.routes').register1(router);
require('./search.routes').register1(router);
require('./export.routes').register1(router);
require('./import.routes').register1(router);

module.exports = router;
