const express = require('express');
const router = express.Router();

// Feature registrars share this Router to preserve the original middleware and route order.
require('../administration/job.routes').register1(router);
require('./file.routes').register1(router);
require('./student-document.routes').register1(router);
require('./system.routes').register1(router);
require('../administration/monitoring.routes').register1(router);
require('./platform.routes').register1(router);
require('./auth.routes').register1(router);
require('./dashboard.routes').register1(router);
require('./notification.routes').register1(router);
require('./dashboard.routes').register2(router);
require('../administration/tenant.routes').register1(router);
require('../administration/user.routes').register1(router);
require('../administration/role.routes').register1(router);
require('../administration/academic.routes').register1(router);
require('./attendance.routes').register1(router);
require('./grade.routes').register1(router);
require('./fee.routes').register1(router);
require('../finance/payroll.routes').register1(router);
require('./equipment.routes').register1(router);
require('./online-payment.routes').register1(router);
require('./appointment.routes').register1(router);
require('./reward.routes').register1(router);
require('./admission.routes').register1(router);
require('./announcement.routes').register1(router);
require('./leave.routes').register1(router);
require('./teaching-schedule.routes').register1(router);
require('./timetable.routes').register1(router);
require('../administration/subscription.routes').register1(router);
require('../administration/template.routes').register1(router);
require('./exam.routes').register1(router);
require('./homework.routes').register1(router);
require('./file.routes').register2(router);
require('./homework.routes').register2(router);
require('./lesson-plan.routes').register1(router);
require('./contact-book.routes').register1(router);
require('./class-life.routes').register1(router);
require('./club.routes').register1(router);
require('./material.routes').register1(router);
require('./library.routes').register1(router);
require('./facility.routes').register1(router);
require('../administration/audit.routes').register1(router);
require('../administration/support.routes').register1(router);
require('./conduct.routes').register1(router);
require('../administration/template.routes').register2(router);
require('./message.routes').register1(router);
require('./calendar.routes').register1(router);
require('./search.routes').register1(router);
require('./export.routes').register1(router);
require('./import.routes').register1(router);

module.exports = router;
