const express = require('express');
const router = express.Router();

// Feature registrars share this Router to preserve the original middleware and route order.
require('../../admin/job.routes').register1(router);
require('../files/file.routes').register1(router);
require('../../admin/student-document.routes').register1(router);
require('../platform/system.routes').register1(router);
require('../../admin/monitoring.routes').register1(router);
require('../platform/platform.routes').register1(router);
require('../identity/auth.routes').register1(router);
require('../platform/dashboard.routes').register1(router);
require('../communication/notification.routes').register1(router);
require('../platform/dashboard.routes').register2(router);
require('../../admin/tenant.routes').register1(router);
require('../../admin/user.routes').register1(router);
require('../../admin/role.routes').register1(router);
require('../../admin/academic.routes').register1(router);
require('../../teacher/attendance.routes').register1(router);
require('../../teacher/grade.routes').register1(router);
require('../../finance/fee.routes').register1(router);
require('../../finance/payroll.routes').register1(router);
require('../campus/equipment.routes').register1(router);
require('../payments/online-payment.routes').register1(router);
require('../scheduling/appointment.routes').register1(router);
require('../../teacher/reward.routes').register1(router);
require('../../admin/admission.routes').register1(router);
require('../communication/announcement.routes').register1(router);
require('../scheduling/leave.routes').register1(router);
require('../scheduling/teaching-schedule.routes').register1(router);
require('../../admin/timetable.routes').register1(router);
require('../../admin/subscription.routes').register1(router);
require('../../admin/template.routes').register1(router);
require('../academics/exam.routes').register1(router);
require('../academics/homework.routes').register1(router);
require('../files/file.routes').register2(router);
require('../academics/homework.routes').register2(router);
require('../../teacher/lesson-plan.routes').register1(router);
require('../../teacher/contact-book.routes').register1(router);
require('../../teacher/class-life.routes').register1(router);
require('../campus/club.routes').register1(router);
require('../../teacher/material.routes').register1(router);
require('../../operations/library.routes').register1(router);
require('../campus/facility.routes').register1(router);
require('../../admin/audit.routes').register1(router);
require('../../admin/support.routes').register1(router);
require('../../teacher/conduct.routes').register1(router);
require('../../admin/template.routes').register2(router);
require('../communication/message.routes').register1(router);
require('../scheduling/calendar.routes').register1(router);
require('../platform/search.routes').register1(router);
require('../files/export.routes').register1(router);
require('../files/import.routes').register1(router);

module.exports = router;
