import { useEffect, useState } from 'react';
import { Button, Card, Form, Input, Modal, Select, Space, Table, Tag, message } from 'antd';
import { useSelector } from 'react-redux';
import { getContactBooksApi, createContactBookApi, publishContactBookApi, replyContactBookApi, getClassesApi, getAcademicYearsApi } from '../../api';
import { can } from '../../util/permissions';

export default function ContactBookPage() {
  const { user } = useSelector(s => s.auth); const manage = can(user, 'contact_books', 'execute'); const parent = user?.role === 'PARENT';
  const [rows, setRows] = useState([]); const [classes, setClasses] = useState([]); const [years, setYears] = useState([]); const [open, setOpen] = useState(false); const [replyTarget, setReplyTarget] = useState(null); const [form] = Form.useForm(); const [replyForm] = Form.useForm();
  const load = async () => { const r = await getContactBooksApi(); if (r?.EC === 0) setRows(r.data || []); else message.error(r?.EM); };
  useEffect(() => { (async () => { if (manage) { const [c, y] = await Promise.all([getClassesApi(), getAcademicYearsApi()]); setClasses(c?.data || []); setYears(y?.data || []); } await load(); })(); }, []);
  const columns = [{ title: 'Ky', render: (_, r) => `${r.periodType} ${r.periodKey}` }, { title: 'Hoc sinh', render: (_, r) => r.studentId?.name }, { title: 'Lop', render: (_, r) => r.classId?.name }, { title: 'Hoc tap', dataIndex: 'academicSummary' }, { title: 'Hanh kiem', dataIndex: 'conductSummary' }, { title: 'Trang thai', dataIndex: 'status', render: v => <Tag color={v === 'PUBLISHED' ? 'green' : 'gold'}>{v}</Tag> }, { title: 'Thao tac', render: (_, r) => <Space>{manage && r.status === 'DRAFT' && <Button size="small" onClick={async () => { const x = await publishContactBookApi(r._id); if (x?.EC === 0) load(); }}>Cong bo</Button>}{parent && r.status === 'PUBLISHED' && <Button size="small" onClick={() => { replyForm.resetFields(); setReplyTarget(r); }}>Phan hoi</Button>}</Space> }];
  return <Card title="So lien lac dinh ky" extra={manage && <Button type="primary" onClick={() => { form.resetFields(); setOpen(true); }}>Tao so lien lac</Button>}><Table rowKey="_id" dataSource={rows} columns={columns} />
    <Modal open={open} title="Tao so lien lac" onCancel={() => setOpen(false)} onOk={() => form.submit()}><Form form={form} layout="vertical" onFinish={async v => { const r = await createContactBookApi(v); if (r?.EC === 0) { setOpen(false); load(); } else message.error(r?.EM); }}><Form.Item name="classId" label="Lop" rules={[{ required: true }]}><Select options={classes.map(x => ({ value: x._id, label: x.name }))} /></Form.Item><Form.Item name="studentId" label="ID hoc sinh" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="academicYearId" label="Nam hoc" rules={[{ required: true }]}><Select options={years.map(x => ({ value: x._id, label: x.name }))} /></Form.Item><Form.Item name="periodType" label="Loai ky" initialValue="MONTH"><Select options={['WEEK', 'MONTH', 'TERM'].map(x => ({ value: x, label: x }))} /></Form.Item><Form.Item name="periodKey" label="Ma ky" rules={[{ required: true }]}><Input placeholder="2026-09" /></Form.Item><Form.Item name="academicSummary" label="Nhan xet hoc tap"><Input.TextArea /></Form.Item><Form.Item name="attendanceSummary" label="Chuyen can"><Input.TextArea /></Form.Item><Form.Item name="conductSummary" label="Hanh kiem"><Input.TextArea /></Form.Item><Form.Item name="teacherNote" label="Ghi chu giao vien"><Input.TextArea /></Form.Item></Form></Modal>
    <Modal open={!!replyTarget} title="Phan hoi so lien lac" onCancel={() => setReplyTarget(null)} onOk={() => replyForm.submit()}><Form form={replyForm} onFinish={async v => { const r = await replyContactBookApi(replyTarget._id, v.parentReply); if (r?.EC === 0) { setReplyTarget(null); load(); } else message.error(r?.EM); }}><Form.Item name="parentReply" label="Noi dung" rules={[{ required: true }]}><Input.TextArea rows={5} /></Form.Item></Form></Modal>
  </Card>;
}
