import { useEffect, useState } from 'react';
import { Button, Card, Form, Input, Modal, Select, Space, Table, Tag, message } from 'antd';
import { useSelector } from 'react-redux';
import { getClassActivitiesApi, createClassActivityApi, publishClassActivityApi, getParentMeetingsApi, createParentMeetingApi, cancelParentMeetingApi, rsvpParentMeetingApi, getClassesApi, getAcademicYearsApi } from '../../api';
import { can } from '../../util/permissions';

export default function ClassLifePage() {
  const { user } = useSelector(s => s.auth); const manage = can(user, 'class_activities', 'execute'); const parent = user?.role === 'PARENT';
  const [activities, setActivities] = useState([]); const [meetings, setMeetings] = useState([]); const [classes, setClasses] = useState([]); const [years, setYears] = useState([]); const [activityOpen, setActivityOpen] = useState(false); const [meetingOpen, setMeetingOpen] = useState(false); const [rsvpTarget, setRsvpTarget] = useState(null); const [activityForm] = Form.useForm(); const [meetingForm] = Form.useForm(); const [rsvpForm] = Form.useForm();
  const load = async () => { const [a, m] = await Promise.all([getClassActivitiesApi(), getParentMeetingsApi()]); if (a?.EC === 0) setActivities(a.data || []); if (m?.EC === 0) setMeetings(m.data || []); };
  useEffect(() => { (async () => { if (manage) { const [c, y] = await Promise.all([getClassesApi(), getAcademicYearsApi()]); setClasses(c?.data || []); setYears(y?.data || []); } await load(); })(); }, []);
  const activityColumns = [{ title: 'Title', dataIndex: 'title' }, { title: 'Class', render: (_, r) => r.classId?.name }, { title: 'Time', dataIndex: 'scheduledAt', render: x => new Date(x).toLocaleString() }, { title: 'Status', dataIndex: 'status', render: x => <Tag>{x}</Tag> }, { title: 'Action', render: (_, r) => manage && r.status === 'DRAFT' && <Button size="small" onClick={async () => { await publishClassActivityApi(r._id); load(); }}>Publish</Button> }];
  const meetingColumns = [{ title: 'Title', dataIndex: 'title' }, { title: 'Class', render: (_, r) => r.classId?.name }, { title: 'Time', dataIndex: 'scheduledAt', render: x => new Date(x).toLocaleString() }, { title: 'Online link', render: (_, r) => r.meetingUrl ? <a href={r.meetingUrl} target="_blank" rel="noreferrer">Join</a> : '-' }, { title: 'Status', dataIndex: 'status' }, { title: 'RSVP', render: (_, r) => parent ? <Button size="small" onClick={() => { rsvpForm.resetFields(); setRsvpTarget(r); }}>{r.response?.status || 'Respond'}</Button> : manage && r.status === 'SCHEDULED' && <Button size="small" onClick={async () => { await cancelParentMeetingApi(r._id); load(); }}>Cancel</Button> }];
  const selectClass = <Select options={classes.map(x => ({ value: x._id, label: x.name }))} />; const selectYear = <Select options={years.map(x => ({ value: x._id, label: x.name }))} />;
  return <Space direction="vertical" style={{ width: '100%' }}><Card title="Class activities" extra={manage && <Button type="primary" onClick={() => setActivityOpen(true)}>New activity</Button>}><Table rowKey="_id" dataSource={activities} columns={activityColumns} /></Card><Card title="Online parent meetings" extra={manage && <Button type="primary" onClick={() => setMeetingOpen(true)}>Schedule meeting</Button>}><Table rowKey="_id" dataSource={meetings} columns={meetingColumns} /></Card>
    <Modal open={activityOpen} title="New class activity" onCancel={() => setActivityOpen(false)} onOk={() => activityForm.submit()}><Form form={activityForm} layout="vertical" onFinish={async v => { const r = await createClassActivityApi({ ...v, scheduledAt: new Date(v.scheduledAt).toISOString() }); if (r?.EC === 0) { setActivityOpen(false); load(); } else message.error(r?.EM); }}><Form.Item name="classId" label="Class" rules={[{ required: true }]}>{selectClass}</Form.Item><Form.Item name="academicYearId" label="Academic year" rules={[{ required: true }]}>{selectYear}</Form.Item><Form.Item name="title" label="Title" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="scheduledAt" label="Time" rules={[{ required: true }]}><Input type="datetime-local" /></Form.Item><Form.Item name="agenda" label="Agenda"><Input.TextArea /></Form.Item></Form></Modal>
    <Modal open={meetingOpen} title="Schedule parent meeting" onCancel={() => setMeetingOpen(false)} onOk={() => meetingForm.submit()}><Form form={meetingForm} layout="vertical" onFinish={async v => { const r = await createParentMeetingApi({ ...v, scheduledAt: new Date(v.scheduledAt).toISOString() }); if (r?.EC === 0) { setMeetingOpen(false); load(); } else message.error(r?.EM); }}><Form.Item name="classId" label="Class" rules={[{ required: true }]}>{selectClass}</Form.Item><Form.Item name="academicYearId" label="Academic year" rules={[{ required: true }]}>{selectYear}</Form.Item><Form.Item name="title" label="Title" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="scheduledAt" label="Time" rules={[{ required: true }]}><Input type="datetime-local" /></Form.Item><Form.Item name="meetingUrl" label="Online URL"><Input /></Form.Item><Form.Item name="agenda" label="Agenda"><Input.TextArea /></Form.Item></Form></Modal>
    <Modal open={!!rsvpTarget} title="Meeting RSVP" onCancel={() => setRsvpTarget(null)} onOk={() => rsvpForm.submit()}><Form form={rsvpForm} onFinish={async v => { const r = await rsvpParentMeetingApi(rsvpTarget._id, v); if (r?.EC === 0) { setRsvpTarget(null); load(); } else message.error(r?.EM); }}><Form.Item name="status" label="Status" initialValue="GOING"><Select options={['GOING', 'MAYBE', 'DECLINED'].map(x => ({ value: x, label: x }))} /></Form.Item><Form.Item name="note" label="Note"><Input.TextArea /></Form.Item></Form></Modal>
  </Space>;
}
