const { test, before, after } = require('node:test'); const assert = require('node:assert/strict'); const mongoose = require('mongoose'); const jwt = require('jsonwebtoken'); const { MongoMemoryReplSet } = require('mongodb-memory-server');
process.env.NODE_ENV = 'test'; process.env.JWT_SECRET = 'admission-test-secret';
const app = require('../src/app'); const cache = require('../src/services/rolePermissionCache'); const { ROLE_PERMISSIONS } = require('../src/constants/permissions'); const { legacyPermissionsToEntries, DEFAULT_ROLE_LEVELS } = require('../src/constants/permissionCatalog'); const Role = require('../src/models/Role'); const School = require('../src/models/School'); const User = require('../src/models/User'); const Admission = require('../src/models/AdmissionApplication');
let mongo; let server; let origin; let school; let admin;
const req = async (method, path, actor, body) => { const headers = { 'Content-Type': 'application/json' }; if (actor) headers.Authorization = `Bearer ${jwt.sign({ _id: actor._id }, process.env.JWT_SECRET)}`; const r = await fetch(`${origin}/v1/api${path}`, { method, headers, body: body ? JSON.stringify(body) : undefined }); return { status: r.status, ...(await r.json()) }; };
before(async () => { mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(mongo.getUri()); await Role.create(Object.entries(ROLE_PERMISSIONS).map(([code, keys]) => ({ code, name: code, level: DEFAULT_ROLE_LEVELS[code], permissions: legacyPermissionsToEntries(keys) }))); await cache.reload(); school = await School.create({ name: 'Admission School', code: 'ADS', subdomain: 'ads' }); admin = await User.create({ name: 'admin', email: 'admin@admission.invalid', role: 'SCHOOL_ADMIN', schoolId: school._id }); server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve)); origin = `http://127.0.0.1:${server.address().port}`; });
after(async () => { await new Promise(resolve => server.close(resolve)); await mongoose.disconnect(); await mongo.stop(); });
test('public applicant submits and tracks an application; staff reviews within school scope', async () => { const body = { schoolCode: 'ADS', applicantName: 'New Student', dateOfBirth: '2012-05-10', guardianName: 'Guardian', guardianPhone: '0900000000', requestedGrade: 7 }; const created = await req('POST', '/admissions/public', null, body); assert.equal(created.status, 201); assert.match(created.data.trackingCode, /^ADM-/); const tracked = await req('GET', `/admissions/public/${created.data.trackingCode}`); assert.equal(tracked.status, 200); assert.equal(tracked.data.applicantName, 'New Student'); const list = await req('GET', '/admissions', admin); assert.equal(list.status, 200); assert.equal(list.data.length, 1); assert.equal((await req('PATCH', `/admissions/${created.data._id}/review`, admin, { status: 'ACCEPTED', reviewNote: 'Welcome' })).status, 200); assert.equal((await req('GET', `/admissions/public/${created.data.trackingCode}`)).data.status, 'ACCEPTED'); assert.equal((await req('PATCH', `/admissions/${created.data._id}/review`, admin, { status: 'REJECTED' })).status, 409); });
test('public validation and tenant scope are enforced', async () => { assert.equal((await req('POST', '/admissions/public', null, { schoolCode: 'MISSING', applicantName: 'x' })).status, 404); const foreignSchool = await School.create({ name: 'Foreign', code: 'FRG', subdomain: 'frg' }); const foreign = await Admission.create({ schoolId: foreignSchool._id, trackingCode: 'ADM-2099-FOREIGN', applicantName: 'Foreign', dateOfBirth: '2012-01-01', guardianName: 'G', guardianPhone: '1', requestedGrade: 1 }); assert.equal((await req('PATCH', `/admissions/${foreign._id}/review`, admin, { status: 'ACCEPTED' })).status, 404); });
