const { test, before, after } = require('node:test'); const assert = require('node:assert/strict'); const mongoose = require('mongoose'); const jwt = require('jsonwebtoken'); const { MongoMemoryReplSet } = require('mongodb-memory-server');
process.env.NODE_ENV = 'test'; process.env.JWT_SECRET = 'rewards-test-secret';
const app = require('../src/app'); const cache = require('../src/services/rolePermissionCache'); const { ROLE_PERMISSIONS } = require('../src/constants/permissions'); const { legacyPermissionsToEntries, DEFAULT_ROLE_LEVELS } = require('../src/constants/permissionCatalog'); const Role = require('../src/models/Role'); const School = require('../src/models/School'); const Class = require('../src/models/Class'); const Year = require('../src/models/AcademicYear'); const User = require('../src/models/User'); const Reward = require('../src/models/RewardDisciplineRecord');
let mongo; let server; let origin; let school; let cls; let year; let student; let teacher; let admin; let parent;
const req = async (method, path, actor, body) => { const headers = { 'Content-Type': 'application/json' }; if (actor) headers.Authorization = `Bearer ${jwt.sign({ _id: actor._id }, process.env.JWT_SECRET)}`; const r = await fetch(`${origin}/v1/api${path}`, { method, headers, body: body ? JSON.stringify(body) : undefined }); return { status: r.status, ...(await r.json()) }; };
before(async () => { mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(mongo.getUri()); await Role.create(Object.entries(ROLE_PERMISSIONS).map(([code, keys]) => ({ code, name: code, level: DEFAULT_ROLE_LEVELS[code], permissions: legacyPermissionsToEntries(keys) }))); await cache.reload(); school = await School.create({ name: 'Rewards School', code: 'RDS', subdomain: 'rds' }); year = await Year.create({ schoolId: school._id, name: '2026', startDate: '2026-08-01', endDate: '2027-06-30' }); cls = await Class.create({ schoolId: school._id, academicYearId: year._id, name: '10R', gradeLevel: 10 }); teacher = await User.create({ name: 'teacher', email: 'teacher@rewards.invalid', role: 'SUBJECT_TEACHER', schoolId: school._id }); admin = await User.create({ name: 'admin', email: 'admin@rewards.invalid', role: 'SCHOOL_ADMIN', schoolId: school._id }); student = await User.create({ name: 'student', email: 'student@rewards.invalid', role: 'STUDENT', schoolId: school._id, classId: cls._id }); parent = await User.create({ name: 'parent', email: 'parent@rewards.invalid', role: 'PARENT', schoolId: school._id, parentOf: [student._id] }); await Class.findByIdAndUpdate(cls._id, { homeroomTeacherId: teacher._id }); server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve)); origin = `http://127.0.0.1:${server.address().port}`; });
after(async () => { await new Promise(resolve => server.close(resolve)); await mongoose.disconnect(); await mongo.stop(); });
test('teacher creates pending reward, admin approves and parent sees approved record', async () => { const created = await req('POST', '/rewards', teacher, { studentId: student._id, classId: cls._id, academicYearId: year._id, type: 'REWARD', title: 'Excellent effort', points: 5 }); assert.equal(created.status, 201); assert.equal(created.data.status, 'PENDING'); assert.equal((await req('GET', '/rewards', parent)).data.length, 0); assert.equal((await req('PATCH', `/rewards/${created.data._id}/review`, admin, { status: 'APPROVED' })).status, 200); const visible = await req('GET', '/rewards', parent); assert.equal(visible.status, 200); assert.equal(visible.data[0].title, 'Excellent effort'); });
test('parent cannot create or view another student reward', async () => { const denied = await req('POST', '/rewards', parent, { studentId: student._id, classId: cls._id, academicYearId: year._id, type: 'DISCIPLINE', title: 'No' }); assert.equal(denied.status, 403); const foreign = await User.create({ name: 'foreign', email: 'foreign@rewards.invalid', role: 'STUDENT', schoolId: school._id }); await Reward.create({ schoolId: school._id, academicYearId: year._id, studentId: foreign._id, classId: cls._id, type: 'DISCIPLINE', title: 'Hidden', status: 'APPROVED', recordedBy: admin._id }); assert.equal((await req('GET', '/rewards', parent)).data.some(x => x.title === 'Hidden'), false); });
