const { test, before, after } = require('node:test'); const assert = require('node:assert/strict'); const mongoose = require('mongoose'); const jwt = require('jsonwebtoken'); const { MongoMemoryReplSet } = require('mongodb-memory-server');
Object.assign(process.env, { NODE_ENV: 'test', JWT_SECRET: 'sso-phone-test', ENTERPRISE_SSO_SECRET: 'enterprise-test-secret', PHONE_LOGIN_ENABLED: 'true' });
const app = require('../src/app'); const cache = require('../src/services/rolePermissionCache'); const { ROLE_PERMISSIONS } = require('../src/constants/permissions'); const { legacyPermissionsToEntries, DEFAULT_ROLE_LEVELS } = require('../src/constants/permissionCatalog'); const Role = require('../src/models/Role'); const School = require('../src/models/School'); const User = require('../src/models/User'); const Notification = require('../src/models/Notification'); const Challenge = require('../src/models/PhoneLoginChallenge'); const sso = require('../src/services/ssoIdentity');
let mongo; let server; let origin; let school; let user;
const request = async (method, route, body, actor) => { const response = await fetch(`${origin}/v1/api${route}`, { method, headers: { 'Content-Type': 'application/json', ...(actor ? { Authorization: `Bearer ${jwt.sign({ _id: actor._id }, process.env.JWT_SECRET)}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) }); return { status: response.status, data: await response.json() }; };
before(async () => { mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(mongo.getUri()); await Role.create(Object.entries(ROLE_PERMISSIONS).map(([code, keys]) => ({ code, name: code, level: DEFAULT_ROLE_LEVELS[code], permissions: legacyPermissionsToEntries(keys) }))); await cache.reload(); school = await School.create({ name: 'SSO School', code: 'SSO', subdomain: 'sso' }); user = await User.create({ name: 'Enterprise User', email: 'enterprise@sso.invalid', phone: '+84901234567', role: 'SCHOOL_ADMIN', schoolId: school._id }); server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve)); origin = `http://127.0.0.1:${server.address().port}`; });
after(async () => { if (server) await new Promise(resolve => server.close(resolve)); await mongoose.disconnect(); if (mongo) await mongo.stop(); });

test('supports phone OTP login and signed enterprise SSO assertion', async () => { const requested = await request('POST', '/auth/phone/request', { phone: user.phone }); assert.equal(requested.status, 200); assert.ok(requested.data.data.challengeId); assert.match(requested.data.data.devCode, /^\d{6}$/); assert.equal((await request('POST', '/auth/phone/verify', { challengeId: requested.data.data.challengeId, code: requested.data.data.devCode })).status, 200); assert.ok((await request('POST', '/auth/phone/verify', { challengeId: requested.data.data.challengeId, code: requested.data.data.devCode })).status >= 400); const assertion = sso.signForTest({ sub: 'entra-user-1', email: user.email, name: user.name, exp: Math.floor(Date.now() / 1000) + 60 }); const login = await request('POST', '/auth/sso', { assertion }); assert.equal(login.status, 200); assert.ok(login.data.data.access_token); assert.equal((await User.findById(user._id)).ssoSubject, 'entra-user-1'); });

test('notification stream emits user events and channel delivery stays safe when gateways are absent', async () => { const event = new Promise(resolve => require('../src/patterns/eventBus').once('notification.created', resolve)); const created = await Notification.create({ userId: user._id, schoolId: school._id, title: 'Realtime', message: 'New alert', type: 'INFO' }); const emitted = await event; assert.equal(String(emitted.userId), String(user._id)); const controller = new AbortController(); const streamResponse = await fetch(`${origin}/v1/api/notifications/stream`, { signal: controller.signal, headers: { Authorization: `Bearer ${jwt.sign({ _id: user._id }, process.env.JWT_SECRET)}` } }); assert.equal(streamResponse.status, 200); assert.match(streamResponse.headers.get('content-type'), /text\/event-stream/); const reader = streamResponse.body.getReader(); await reader.read(); const nextChunk = reader.read(); await Notification.create({ userId: user._id, schoolId: school._id, title: 'Streamed', message: 'Realtime event', type: 'INFO' }); const streamed = await Promise.race([nextChunk, new Promise((_, reject) => setTimeout(() => reject(new Error('SSE event timeout')), 1000))]); assert.match(new TextDecoder().decode(streamed.value), /Streamed/); controller.abort(); await reader.cancel().catch(() => {}); const delivered = await request('POST', `/notifications/${created._id}/deliver`, { channels: ['SMS', 'ZALO', 'PUSH'] }, user); assert.equal(delivered.status, 200); assert.equal(delivered.data.data.results.SMS.status, 'SKIPPED'); const stored = await Notification.findById(created._id); assert.equal(stored.delivery.ZALO.status, 'SKIPPED'); assert.equal(await Challenge.countDocuments({}), 1); });
