import { useEffect, useState } from 'react';
import { Button, Card, Form, Input, InputNumber, Modal, Select, Space, Table, Tag, message } from 'antd';
import { useSelector } from 'react-redux';
import { createEquipmentApi, createEquipmentMaintenanceApi, getEquipmentApi, getEquipmentMaintenanceApi, updateEquipmentMaintenanceApi } from '../../api';
import { can } from '../../util/permissions';

const EquipmentMaintenancePage = () => {
  const { user } = useSelector(s => s.auth); const manage = can(user, 'facilities', 'create'); const execute = can(user, 'facilities', 'execute');
  const [equipment, setEquipment] = useState([]); const [maintenance, setMaintenance] = useState([]); const [equipmentOpen, setEquipmentOpen] = useState(false); const [maintenanceOpen, setMaintenanceOpen] = useState(false); const [saving, setSaving] = useState(false); const [equipmentForm] = Form.useForm(); const [maintenanceForm] = Form.useForm();
  const load = async () => { const [assets, records] = await Promise.all([getEquipmentApi(), getEquipmentMaintenanceApi()]); if (assets?.EC === 0) setEquipment(assets.data || []); if (records?.EC === 0) setMaintenance(records.data || []); };
  useEffect(() => { load(); }, []);
  const transition = async (row, status) => { const result = await updateEquipmentMaintenanceApi(row._id, { status, resolution: status === 'RESOLVED' ? 'Resolved after inspection' : '' }); if (result?.EC === 0) { message.success(result.EM); load(); } else message.error(result?.EM); };
  return <Space direction="vertical" style={{ width: '100%' }}>
    <Card title="Equipment inventory" extra={manage && <Button type="primary" onClick={() => setEquipmentOpen(true)}>Add equipment</Button>}><Table rowKey="_id" dataSource={equipment} columns={[{ title: 'Code', dataIndex: 'code' }, { title: 'Name', dataIndex: 'name' }, { title: 'Category', dataIndex: 'category' }, { title: 'Location', dataIndex: 'location' }, { title: 'Quantity', dataIndex: 'quantity' }, { title: 'Status', dataIndex: 'status', render: value => <Tag>{value}</Tag> }]} /></Card>
    <Card title="Maintenance requests" extra={<Button onClick={() => setMaintenanceOpen(true)}>Report issue</Button>}><Table rowKey="_id" dataSource={maintenance} columns={[{ title: 'Equipment', render: (_, row) => `${row.equipmentId?.code || ''} - ${row.equipmentId?.name || ''}` }, { title: 'Issue', dataIndex: 'issue' }, { title: 'Priority', dataIndex: 'priority', render: value => <Tag color={value === 'URGENT' ? 'red' : undefined}>{value}</Tag> }, { title: 'Status', dataIndex: 'status', render: value => <Tag>{value}</Tag> }, { title: 'Reported by', render: (_, row) => row.reportedBy?.name || '-' }, execute ? { title: 'Actions', render: (_, row) => <Space>{row.status === 'OPEN' && <Button size="small" onClick={() => transition(row, 'IN_PROGRESS')}>Start</Button>}{['OPEN', 'IN_PROGRESS'].includes(row.status) && <Button size="small" type="primary" onClick={() => transition(row, 'RESOLVED')}>Resolve</Button>}{['OPEN', 'IN_PROGRESS'].includes(row.status) && <Button size="small" danger onClick={() => transition(row, 'CANCELLED')}>Cancel</Button>}</Space> } : {}].filter(item => item.title)} /></Card>
    <Modal open={equipmentOpen} title="Add equipment" confirmLoading={saving} onCancel={() => !saving && setEquipmentOpen(false)} onOk={() => equipmentForm.submit()}><Form form={equipmentForm} layout="vertical" onFinish={async values => { setSaving(true); try { const result = await createEquipmentApi(values); if (result?.EC !== 0) return message.error(result?.EM); message.success('Created'); setEquipmentOpen(false); equipmentForm.resetFields(); load(); } finally { setSaving(false); } }}><Form.Item name="code" label="Code" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="name" label="Name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="category" label="Category" initialValue="GENERAL"><Input /></Form.Item><Form.Item name="serialNumber" label="Serial number"><Input /></Form.Item><Form.Item name="location" label="Location"><Input /></Form.Item><Form.Item name="quantity" label="Quantity" initialValue={1}><InputNumber min={1} style={{ width: '100%' }} /></Form.Item><Form.Item name="note" label="Note"><Input.TextArea /></Form.Item></Form></Modal>
    <Modal open={maintenanceOpen} title="Report maintenance issue" confirmLoading={saving} onCancel={() => !saving && setMaintenanceOpen(false)} onOk={() => maintenanceForm.submit()}><Form form={maintenanceForm} layout="vertical" onFinish={async values => { setSaving(true); try { const result = await createEquipmentMaintenanceApi(values); if (result?.EC !== 0) return message.error(result?.EM); message.success('Reported'); setMaintenanceOpen(false); maintenanceForm.resetFields(); load(); } finally { setSaving(false); } }}><Form.Item name="equipmentId" label="Equipment" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={equipment.filter(item => item.status !== 'RETIRED').map(item => ({ value: item._id, label: `${item.code} - ${item.name}` }))} /></Form.Item><Form.Item name="issue" label="Issue" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="priority" label="Priority" initialValue="MEDIUM"><Select options={['LOW', 'MEDIUM', 'HIGH', 'URGENT'].map(value => ({ value, label: value }))} /></Form.Item><Form.Item name="description" label="Details"><Input.TextArea /></Form.Item><Form.Item name="cost" label="Estimated cost" initialValue={0}><InputNumber min={0} style={{ width: '100%' }} /></Form.Item></Form></Modal>
  </Space>;
};
export default EquipmentMaintenancePage;
