import { useEffect, useState } from 'react';
import { Button, Card, Select, Space, Table, message } from 'antd';
import { compareSchoolsApi, exportSchoolComparisonApi, getSchoolsApi } from '../../api';
const SchoolComparisonPage = () => {
  const [schools, setSchools] = useState([]); const [selected, setSelected] = useState([]); const [rows, setRows] = useState([]);
  useEffect(() => { getSchoolsApi().then(result => result?.EC === 0 && setSchools(result.data || [])); }, []);
  const compare = async () => { if (selected.length < 2) return message.warning('Chọn ít nhất hai trường'); const result = await compareSchoolsApi(selected); if (result?.EC === 0) setRows(result.data || []); else message.error(result?.EM); };
  const download = async format => { if (selected.length < 2) return message.warning('Chọn ít nhất hai trường'); const blob = await exportSchoolComparisonApi(format, selected); if (!(blob instanceof Blob)) return message.error('Không thể xuất báo cáo'); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `doi-chieu-lien-truong.${format}`; link.click(); URL.revokeObjectURL(url); };
  return <Card title="Đối chiếu liên trường"><Space wrap style={{ marginBottom: 16 }}><Select mode="multiple" showSearch optionFilterProp="label" value={selected} onChange={setSelected} options={schools.map(school => ({ value: school._id, label: `${school.name} (${school.code})` }))} style={{ minWidth: 420 }} /><Button type="primary" onClick={compare}>Đối chiếu</Button><Button onClick={() => download('xlsx')}>Xuất Excel</Button><Button onClick={() => download('pdf')}>Xuất PDF</Button></Space><Table rowKey={row => row.school._id} dataSource={rows} columns={[{ title: 'Trường', render: (_, row) => `${row.school.name} (${row.school.code})` }, { title: 'Học sinh', dataIndex: 'students' }, { title: 'Giáo viên', dataIndex: 'teachers' }, { title: 'Lớp', dataIndex: 'classes' }, { title: 'Điểm TB', dataIndex: 'gradeAverage', render: value => value == null ? '-' : Number(value).toFixed(2) }, { title: 'Tỷ lệ có mặt', dataIndex: 'attendanceRate', render: value => value == null ? '-' : `${value}%` }, { title: 'Nợ còn lại', dataIndex: 'outstandingAmount', render: value => Number(value).toLocaleString('vi-VN') }]} /></Card>;
};
export default SchoolComparisonPage;
