const fs = require('node:fs/promises');
const path = require('node:path');
const { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } = require('@aws-sdk/client-s3');
const config = require('../config/fileStorage');

const localPath = key => {
  // Keys are generated by the server, never derived from filenames or request paths.
  if (!/^[a-f0-9]{24}\/[a-f0-9-]{36}$/.test(key)) throw new Error('Invalid storage key');
  return path.join(config().root, ...key.split('/'));
};
const createS3Storage = (client) => ({
  put: asset => client.send(new PutObjectCommand({ Bucket: asset.bucket, Key: asset.key, Body: asset.buffer, ContentType: asset.mimeType })),
  read: async asset => (await client.send(new GetObjectCommand({ Bucket: asset.bucket, Key: asset.key }))).Body,
  remove: asset => client.send(new DeleteObjectCommand({ Bucket: asset.bucket, Key: asset.key })),
});
let s3;
const adapter = driver => {
  if (driver === 'local') return {
    put: async asset => {
      const target = localPath(asset.key);
      await fs.mkdir(path.dirname(target), { recursive: true, mode: 0o700 });
      await fs.writeFile(target, asset.buffer, { flag: 'wx', mode: 0o600 });
    },
    read: async asset => {
      const handle = await fs.open(localPath(asset.key), 'r');
      return handle.createReadStream();
    },
    remove: async asset => { await fs.rm(localPath(asset.key), { force: true }); },
  };
  if (driver !== 's3') throw new Error('Unknown storage driver');
  s3 ||= createS3Storage(new S3Client({ region: process.env.AWS_REGION || 'us-east-1',
    ...(process.env.FILE_S3_ENDPOINT ? { endpoint: process.env.FILE_S3_ENDPOINT } : {}),
    forcePathStyle: process.env.FILE_S3_FORCE_PATH_STYLE === 'true' }));
  return s3;
};
module.exports = { adapter, createS3Storage, localPath };
